export type LoreEntry={section:string;title:string;subtitle?:string;text:string;accent?:string;year?:string};
export const loreSections=['Tout','Fondements','École','Maisons','Lieux','Chronologie','Glossaire','Créatures','Société','Familles','Personnalités','Razeball'];
export const lore:LoreEntry[]=[
{section:'Fondements',title:"L’Écho",subtitle:'Le Premier Murmure',text:"Force originelle qui traverse toute chose depuis la naissance de l’univers. L’Écho ne produit aucun sort et n’obéit à aucune formule : il rend simplement toute magie possible."},
{section:'Fondements',title:'La Résonance',text:"Fréquence propre à chaque être, fondée sur deux prédispositions génétiques : ressentir l’Écho et le contrôler. Ceux qui possèdent les deux peuvent produire un Flux exploitable."},
{section:'Fondements',title:'Le Flux',text:"Énergie née de la rencontre entre l’Écho et une Résonance forte. D’abord instinctif chez les jeunes sorciers, il se dirige par l’intention, le geste, l’incantation et un catalyseur."},
{section:'Fondements',title:'Le Voile',text:"Phénomène naturel autour des lieux très chargés en Flux, qui les dissimule aux Sans-Flux. Un voile artificiel peut aussi être posé, superposé ou perturber un Voile naturel."},
{section:'Fondements',title:'Résonants',text:"Sorciers capables de ressentir et contrôler l’Écho. Ils ont accès à l’éducation magique et doivent préserver le Secret face aux Sans-Flux."},
{section:'Fondements',title:'Sans-Flux',text:"Majorité de l’humanité, dont la Résonance reste trop faible pour percevoir ou manipuler la magie. Leur esprit rationalise généralement les phénomènes inexpliqués."},
{section:'Fondements',title:'Dissonants',text:"Nés parmi les Sans-Flux avec une prédisposition rare. Avec une seule, ils peuvent passer pour des prodiges ou médiums. Avec les deux, ils deviennent de véritables Résonants."},
{section:'Fondements',title:'Magie d’usage',text:"Magie du quotidien, des duels, des soins et des enchantements. Elle canalise le Flux au moyen de l’intention, d’un geste, d’une formule et souvent d’un catalyseur."},
{section:'Fondements',title:'Runomancie',text:"Inscrit le Flux dans la durée. Chaque rune traduit une harmonie de l’Écho et plusieurs runes forment un accord capable de protéger, verrouiller, mémoriser ou stabiliser."},
{section:'École',title:'Elderwood',subtitle:'Grande école du Royaume-Uni',text:"Seule grande école britannique de sorcellerie. Dissimulée par un puissant Voile et bâtie autour de la Source de Vehr, elle apprend aux jeunes Résonants à comprendre leur Flux."},
{section:'École',title:'La Source de Vehr',text:"Bassin découvert par Falcon en 1298. Son eau révèle la couleur de l’âme et du Flux d’un Résonant : bleu, vert, orange ou violet."},
{section:'Maisons',title:'Aerwyn',subtitle:'Le Pégase · Flux bleu',text:"Honneur, protection, constance. Fondée par Althea Aerwyn. Ses membres choisissent un code et s’y tiennent même lorsque cela devient inconfortable.",accent:'#466c9d'},
{section:'Maisons',title:'Brumval',subtitle:'Le Grand Ours · Flux vert',text:"Loyauté, camaraderie, courage. Fondée par Hector Brumval. Ce qu’on construit ensemble vaut plus que ce qu’on obtient seul.",accent:'#4f7758'},
{section:'Maisons',title:'Falcon',subtitle:'Le Faucon pèlerin · Flux orange',text:"Savoir, curiosité, sagesse. Fondée par Eldric Falcon. Comprendre une situation vaut mieux que la forcer.",accent:'#b77936'},
{section:'Maisons',title:'Venatrix',subtitle:'La Pieuvre géante · Flux violet',text:"Ambition, maîtrise, influence. Fondée par Selena Venatrix. Ses membres construisent discrètement les chemins qui mènent à leurs objectifs.",accent:'#725b91'},
{section:'Lieux',title:'La Bibliothèque',subtitle:'Savoir et archives',text:'Manuels, grimoires anciens et sections interdites, gérés par un bibliothécaire et des fées des bois.'},
{section:'Lieux',title:'Infirmerie Grimshaw',subtitle:'Soins et convalescence',text:'Nommée en hommage à Edith Grimshaw, ancienne médicomage d’Elderwood.'},
{section:'Lieux',title:'Les Jardins',subtitle:'Botanique et repos',text:'Transformés par la proximité de la Source, ils servent à l’étude et au repos.'},
{section:'Lieux',title:'La Grande Volière',subtitle:'Courrier et messagers',text:'Tour ouverte accueillant chouettes, corbeaux et faucons messagers.'},
{section:'Lieux',title:'Pavillon des Compagnons',subtitle:'Ménagerie',text:'Abrite les familiers, sous la garde du garde-chasse et du professeur de magizoologie.'},
{section:'Lieux',title:'Atelier des Catalyseurs',text:'Salle où les élèves entretiennent et réparent baguettes, sceptres et bâtons.'},
{section:'Lieux',title:'Forge Runique',text:'Lieu d’expériences profondément enfoui sous le château et réservé aux élèves avancés.'},
{section:'Lieux',title:'Cuisines Hearthbane',text:'Vastes cuisines toujours en mouvement, situées sous la Grande Salle.'},
{section:'Lieux',title:'La Grande Salle',subtitle:'Cœur du château',text:'Seul lieu où les quatre maisons se retrouvent sous un même toit.'},
{section:'Lieux',title:'Observatoire des Hautes-Vues',subtitle:'Salle commune Falcon',text:'Dans les plus hautes tours, accessible par un pont suspendu.'},
{section:'Lieux',title:'La Veillée Bleue',subtitle:'Salle commune Aerwyn',text:'Sous un toit de verre incassable, parmi les armures des anciens défenseurs.'},
{section:'Lieux',title:'Salon des Ombres',subtitle:'Salle commune Venatrix',text:'Dans les sous-sols, avec deux baies vitrées ouvertes sur les profondeurs du lac.'},
{section:'Lieux',title:'Le Grand Foyer',subtitle:'Salle commune Brumval',text:'La plus chaleureuse, autour d’un feu qui ne s’éteint jamais.'},
{section:'Lieux',title:'Brûlebrume',subtitle:'Zone à haut risque',text:'Brume grise et corrosive, sanctuaire des Arachnides d’Éther.'},
{section:'Lieux',title:'Terrain de Razeball',text:'Structure circulaire taillée dans la falaise, cœur de la vie extrascolaire.'},
{section:'Lieux',title:'Shedwood',subtitle:'Village voisin',text:'Une statue y rend hommage à Maeve Storm.'},
{section:'Chronologie',title:'Découverte de la Source',year:'1298',text:'Falcon découvre la Source de Vehr et ses quatre couleurs majeures.'},
{section:'Chronologie',title:'Fondation d’Elderwood',year:'1300',text:'Falcon, Aerwyn, Venatrix et Brumval fondent l’école.'},
{section:'Chronologie',title:'Sentence de Mireille',year:'1432',text:'Gwendolyn Caerwyn applique une sanction controversée qui divise encore Aerwyn.'},
{section:'Chronologie',title:'La Flamme Ouverte',year:'1463',text:'Elspeth Hearthbane organise le premier festival ouvert à toutes les entités magiques.'},
{section:'Chronologie',title:'Codification du Razeball',year:'1863',text:'Corvinus Valemont établit le règlement moderne du sport.'},
{section:'Chronologie',title:'Le Grand Confinement',year:'1944–1945',text:'Cassiopée Valemont rédige les décrets d’isolation du monde magique.'},
...['Écho|Origine de toute magie','Résonance|Réponse propre de chaque être à l’Écho','Flux|Énergie manipulable née de l’Écho et de la Résonance','Sans-Flux|Humain dont la Résonance ne produit pas de Flux exploitable','Dissonant|Personne issue du monde Sans-Flux avec une prédisposition à la Résonance','Voile|Phénomène dissimulant un lieu magique aux Sans-Flux','Catalyseur|Instrument qui canalise le Flux du sorcier','Source de Vehr|Bassin révélant la couleur du Flux','Razeball|Sport sorcier international, aussi appelé le Raze'].map(x=>{const [title,text]=x.split('|');return{section:'Glossaire',title,text}}),
{section:'Créatures',title:'Brisecerat',text:'Créature côtière discrète au dos couvert de cératine, recherchée pour les protections accessibles et durables.'},
{section:'Créatures',title:'Scalvignus',text:'Cerf forestier couvert d’écailles. Ses bois tombés naturellement servent à certains catalyseurs.'},
{section:'Créatures',title:'Échoïde',text:'Empreinte vivante d’une structure runique, portant savoir et personnalité de son créateur. Sa mémoire fragmentée peut le rendre dangereux.'},
{section:'Créatures',title:'Ornicabal',text:'Créature semi-aquatique sociable et apprivoisable, mais territoriale. Ses écailles hydrophobes servent aux équipements imperméables.'},
{section:'Société',title:'AMRU',subtitle:'Autorités Magiques du Royaume-Uni',text:'Autorité centrale chargée des lois, de la sécurité, des institutions et de la régulation magique. Elderwood conserve son autonomie mais reste un partenaire essentiel.'},
{section:'Familles',title:'Caerwyn',subtitle:'Aerwyn · Le serment',text:'Protecteurs d’Elderwood depuis sa fondation, associés à l’honneur et à la parole donnée. Représentés par Seraphine Caerwyn.'},
{section:'Familles',title:'Hearthbane',subtitle:'Brumval · Le foyer',text:'Gardiens du premier feu et de la Flamme Ouverte. Représentés par Petra Hearthbane.'},
{section:'Familles',title:'Valemont',subtitle:'Falcon · Le savoir',text:'Gardiens des archives, influents dans l’enseignement, l’administration et le Razeball. Représentés par Ebenezer Valemont.'},
{section:'Familles',title:'Dravenholt',subtitle:'Venatrix · L’influence',text:'Famille des cercles politiques et mondains, maîtresse des réseaux et des décisions discrètes. Représentée par Isolde Dravenholt.'},
{section:'Familles',title:'Belladorn',text:'Alchimistes indépendants de la Chaudronnerie, tournés vers l’expérimentation et l’herboristerie parfois dangereuses.'},
{section:'Familles',title:'Ravenscroft',text:'Lignée de runomanciens méthodiques : comprendre avant d’intervenir, préparer avant d’agir.'},
{section:'Familles',title:'Glenhart',text:'Spécialistes des créatures : Compagnons tournés vers le soin et Arpenteurs vers l’exploration sauvage.'},
{section:'Personnalités',title:'Arthurius Glenwood',subtitle:'Directeur d’Elderwood',text:'Grand sorcier calme et expérimenté, protecteur de l’école et symbole de stabilité.'},
{section:'Personnalités',title:'Edith Grimshaw',subtitle:'Ancienne médicomage',text:'Sauva des élèves en reliant leur magie à la sienne et ne retrouva jamais entièrement ses pouvoirs.'},
{section:'Personnalités',title:'Alistair Valemont',subtitle:'Haut placé de l’AMRU',text:'Défenseur influent et conservateur d’une application stricte du Secret magique.'},
{section:'Personnalités',title:'Cadoc Caerwyn',subtitle:'Celui qui tint la ligne',text:'Maintint trois jours une barrière face au Léviathan de Lituya en 1958 et y perdit un bras.'},
{section:'Personnalités',title:'Bénédicte Hearthbane',text:'Aida à évacuer les familles résonantes lors du Grand Incendie de Londres de 1666.'},
{section:'Personnalités',title:'Edgar Ravenscroft',text:'Neutralisa progressivement un immense Échoïde et fonda la méthode Ravenscroft.'},
{section:'Personnalités',title:'Rowena Glenhart',text:'Mena l’expédition de Shedwood en 1890. Deux membres disparurent et elle garda le silence sur les derniers jours.'},
{section:'Razeball',title:'Le Raze',text:'Sport aérien joué autour d’une sphère métallique à envoyer dans le Cœur adverse. Six joueurs : un Gardien et cinq Finishers, Playmakers, Enforcers ou Lights Out. Codifié en 1863, mondial depuis 1896.'}
];
