export type LoreEntry={section:string;title:string;subtitle?:string;text:string;accent?:string;year?:string};
export const loreSections=['Tout','Fondements','École','Maisons','Lieux','Chronologie','Glossaire','Créatures','Société','Familles','Personnalités','Razeball'];
export const lore:LoreEntry[]=[
{section:'Fondements',title:"L’Écho",subtitle:'Le Premier Murmure',text:"Force originelle qui traverse toute chose depuis la naissance de l’univers. L’Écho ne produit aucun sort et n’obéit à aucune formule : il rend simplement toute magie possible."},
{section:'Fondements',title:'La Résonance',text:"Fréquence propre à chaque être, fondée sur deux prédispositions génétiques : ressentir l’Écho et le contrôler. Ceux qui possèdent les deux peuvent produire un Flux exploitable."},
{section:'Fondements',title:'Le Flux',text:"Énergie née de la rencontre entre l’Écho et une Résonance forte. D’abord instinctif chez les jeunes sorciers, il se dirige par l’intention, le geste, l’incantation et un catalyseur."},
{section:'Fondements',title:'Le Voile',text:`Chaque lieu possède, comme les êtres vivants, sa propre Résonance. Une forte concentration de Flux peut faire naître un Voile, phénomène qui rend le lieu difficile à remarquer pour les Sans-Flux.

Les écoles et sanctuaires magiques se construisent souvent dans ces lieux voilés. Elderwood en est l’exemple le plus connu, dissimulée du monde Sans-Flux par un Voile naturel particulièrement puissant. Un lieu trop chargé en Flux peut toutefois devenir imprévisible : c’est ainsi que naissent les Échoïdes, souvenirs figés dans une rune instable.

On distingue le Voile naturel, formé spontanément autour d’un lieu fortement chargé en Flux, du voile artificiel, posé volontairement par des sorciers. Un voile artificiel peut se superposer à un Voile naturel existant et parfois même le perturber.`},
{section:'Fondements',title:'Résonants',text:`Ceux que le langage courant appelle des sorciers. Leur Résonance est assez importante et claire pour répondre à l’Écho et faire naître un Flux exploitable.

Ils peuvent apprendre la magie, canaliser leur Flux à travers une baguette, un sceptre ou tout autre catalyseur, pratiquer des sorts et utiliser des objets enchantés. Être Résonant implique l’accès à une éducation magique, à des droits et à des devoirs, notamment la responsabilité de ne pas exposer la magie aux Sans-Flux.`},
{section:'Fondements',title:'Sans-Flux',text:`Ils représentent la majorité de l’humanité. Ils possèdent une Résonance, comme toute chose existante, mais elle est trop faible : ils ne perçoivent pas la magie, ne produisent pas de Flux suffisant et ne peuvent pas le manipuler.

Cela ne signifie pas qu’ils soient totalement séparés du monde magique. Ils peuvent percevoir certains phénomènes, être touchés par leurs effets ou traverser le Voile lorsqu’il est affaibli, devenant alors témoins de choses qu’ils ne s’expliquent pas. Leur esprit tend naturellement à rationaliser ce qu’il ne comprend pas et à se tourner vers la science.`},
{section:'Fondements',title:'Dissonants',text:`Cas particuliers nés dans le monde Sans-Flux, souvent de parents Sans-Flux, mais héritant d’une prédisposition génétique rare liée à la Résonance.

La Résonance repose sur deux prédispositions : ressentir l’Écho et le contrôler. La plupart des Dissonants n’en portent qu’une seule ; ils sont alors connus dans le monde humain comme des génies, prodiges, voyants ou médiums. Les cas les plus rares possèdent les deux à la fois et deviennent de véritables Résonants au sein d’une lignée Sans-Flux.`},
{section:'Fondements',title:'Magie d’usage',text:`La Magie d’usage est la forme la plus répandue. Elle correspond à la magie pratiquée dans la vie quotidienne : à l’école, pendant les duels, dans les soins, les enchantements simples ou les actes magiques courants.

Elle repose sur l’intention du sorcier, sa capacité à canaliser son Flux, puis à lui donner une direction par un geste, une formule ou un catalyseur. L’apparition des baguettes a profondément transformé cette pratique en concentrant le Flux dans un catalyseur adapté, ce qui permet d’affiner les gestes et de transmettre plus facilement le savoir.`},
{section:'Fondements',title:'Runomancie',text:`La Runomancie suit une logique différente : là où la Magie d’usage agit par le geste et l’instant, elle cherche à inscrire le Flux dans la durée.

Les runes ne sont pas de simples lettres, mais des fréquences retranscrites sous forme de symboles. Chaque rune représente une harmonie observée dans l’Écho. Une rune seule possède une influence limitée, mais plusieurs runes forment un accord capable d’orienter durablement la magie : protéger un lieu, verrouiller un passage, conserver une mémoire ou stabiliser un enchantement.`},
{section:'École',title:'Elderwood',subtitle:'Grande école du Royaume-Uni',text:`Seule grande école de sorcellerie du Royaume-Uni, Elderwood forme les jeunes Résonants à comprendre et maîtriser leur Flux. Dissimulée par un Voile puissant, elle est bâtie autour d’une source de magie unique et garde encore aujourd’hui bien des secrets.

En l’an 1298, Falcon découvrit sur une île sans nom, protégée par un voile magique, une source d’eau capable de révéler la couleur de l’âme de quiconque s’y reflète : la Source de Vehr, plus simplement appelée la Source.

Il identifia quatre couleurs majeures : bleu, vert, violet et orange. Il rechercha ensuite trois personnes dont l’âme correspondait aux couleurs qu’il n’incarnait pas lui-même : Aerwyn, Venatrix et Brumval. En l’an 1300, tous les quatre fondèrent Elderwood.`},
{section:'École',title:'La Source de Vehr',text:"Bassin découvert par Falcon en 1298. Son eau révèle la couleur de l’âme et du Flux d’un Résonant : bleu, vert, orange ou violet."},
{section:'Maisons',title:'Aerwyn',subtitle:'Le Pégase · Flux bleu',text:`« J’agis avec droiture et intégrité. »

Honneur, protection et constance. Fondée par Althea Aerwyn, cette maison est celle du courage et du serment tenu. Les Aerwyn agissent selon un code qu’ils se sont choisi et s’y tiennent même lorsque cela devient inconfortable.

La famille Caerwyn, présente depuis la première nuit de la construction d’Elderwood, lui est historiquement liée.`,accent:'#466c9d'},
{section:'Maisons',title:'Brumval',subtitle:'Le Grand Ours · Flux vert',text:`« Ma force, c’est de rester fidèle à ceux qui comptent sur moi. »

Loyauté, camaraderie et courage. Fondée par Hector Brumval, cette maison est celle du foyer et de la fidélité. Les Brumval croient que ce que l’on construit ensemble vaut plus que ce que l’on obtient seul.

La famille Hearthbane est liée à Brumval depuis les premières années d’Elderwood et garde les traditions du premier feu.`,accent:'#4f7758'},
{section:'Maisons',title:'Falcon',subtitle:'Le Faucon pèlerin · Flux orange',text:`« La connaissance est une arme redoutable. »

Savoir, curiosité et sagesse. Fondée par Eldric Falcon, la maison Falcon est celle de l’intelligence mise au service du monde. Ses membres considèrent que comprendre une situation vaut mieux que la forcer ; on leur reproche parfois de vivre si haut dans leurs réflexions qu’ils oublient ceux qui marchent à leurs côtés.

La famille Valemont garde une relation privilégiée avec Falcon et les archives de l’école.`,accent:'#b77936'},
{section:'Maisons',title:'Venatrix',subtitle:'La Pieuvre géante · Flux violet',text:`« Je tire les ficelles, proprement et sans bruit. »

Ambition, maîtrise et influence. Fondée par Selena Venatrix, cette maison est celle de la stratégie et de la dissimulation. Ses membres construisent les chemins qui leur permettent d’obtenir ce qu’ils veulent.

La famille Dravenholt lui est historiquement proche et exerce son influence dans les cercles du Ministère.`,accent:'#725b91'},
{section:'Lieux',title:'La Bibliothèque',subtitle:'Savoir et archives',text:'Manuels, grimoires anciens et sections interdites, gérés par un bibliothécaire et des fées des bois.'},
{section:'Lieux',title:'Infirmerie Grimshaw',subtitle:'Soins et convalescence',text:'Nommée en hommage à Edith Grimshaw, ancienne médicomage d’Elderwood.'},
{section:'Lieux',title:'Les Jardins',subtitle:'Botanique et repos',text:'Transformés par la proximité de la Source, ils servent à l’étude et au repos.'},
{section:'Lieux',title:'La Grande Volière',subtitle:'Courrier et messagers',text:'Tour ouverte accueillant chouettes, corbeaux et faucons messagers.'},
{section:'Lieux',title:'Pavillon des Compagnons',subtitle:'Ménagerie',text:'Abrite les familiers, sous la garde du garde-chasse et du professeur de magizoologie.'},
{section:'Lieux',title:'Atelier des Catalyseurs',subtitle:'Entretien des catalyseurs',text:'Salle technique où les élèves apprennent à entretenir et réparer baguettes, sceptres et bâtons.'},
{section:'Lieux',title:'Forge Runique',subtitle:'Runomancie et expériences',text:'Profondément enfouie sous le château, cette forge est réservée aux élèves avancés.'},
{section:'Lieux',title:'Cuisines Hearthbane',subtitle:'Repas de l’école',text:'Vastes et toujours en mouvement, elles sont situées sous la Grande Salle.'},
{section:'Lieux',title:'La Grande Salle',subtitle:'Cœur du château',text:'Seul lieu où les quatre maisons se retrouvent sous un même toit.'},
{section:'Lieux',title:'Observatoire des Hautes-Vues',subtitle:'Salle commune de Falcon',text:'Nichée dans les plus hautes tours du château et accessible par un pont suspendu, Falcon y aurait conçu les premières bases du système d’apprentissage.'},
{section:'Lieux',title:'La Veillée Bleue',subtitle:'Salle commune d’Aerwyn',text:'Éclairée par un toit de verre incassable, elle expose les armures des anciens défenseurs du château.'},
{section:'Lieux',title:'Salon des Ombres',subtitle:'Salle commune de Venatrix',text:'Niché dans les sous-sols, il s’ouvre sur les profondeurs du lac par deux grandes baies vitrées.'},
{section:'Lieux',title:'Le Grand Foyer',subtitle:'Salle commune de Brumval',text:'La plus chaleureuse du château, réchauffée par un feu qui ne s’éteint jamais.'},
{section:'Lieux',title:'Brûlebrume',subtitle:'Zone à haut risque',text:'Brume grise et corrosive, sanctuaire des Arachnides d’Éther.'},
{section:'Lieux',title:'Terrain de Razeball',text:'Structure circulaire taillée dans la falaise, cœur de la vie extrascolaire.'},
{section:'Lieux',title:'Shedwood',subtitle:'Village voisin',text:'Une statue y rend hommage à Maeve Storm.'},
{section:'Chronologie',title:'Découverte de la Source',year:'1298',text:'Falcon découvre la Source de Vehr et ses quatre couleurs majeures.'},
{section:'Chronologie',title:'Fondation d’Elderwood',year:'1300',text:'Falcon, Aerwyn, Venatrix et Brumval fondent l’école.'},
{section:'Chronologie',title:'Sentence de Mireille',year:'1432',text:'Gwendolyn Caerwyn applique une sanction controversée qui divise encore Aerwyn.'},
{section:'Chronologie',title:'La Flamme Ouverte',year:'1463',text:'Elspeth Hearthbane organise le premier festival ouvert à toutes les entités magiques.'},
{section:'Chronologie',title:'Codification du Razeball',year:'1863',text:'Corvinus Valemont établit le règlement moderne du sport.'},
{section:'Chronologie',title:'Le Grand Confinement',year:'1944–1945',text:'Cassiopée Valemont rédige les décrets d’isolation du monde magique.'},
...['Écho|Origine de toute magie','Résonance|Réponse propre de chaque être à l’Écho','Flux|Énergie manipulable née de l’Écho et de la Résonance','Sans-Flux|Humain dont la Résonance ne produit pas de Flux exploitable','Dissonant|Personne issue du monde Sans-Flux avec une prédisposition à la Résonance','Voile|Phénomène dissimulant un lieu magique aux Sans-Flux','Catalyseur|Instrument qui canalise le Flux du sorcier','Source de Vehr|Bassin révélant la couleur du Flux','Razeball|Sport sorcier international, aussi appelé le Raze'].map(x=>{const [title,text]=x.split('|');return{section:'Glossaire',title,text}}),
{section:'Créatures',title:'Brisecerat',text:`Créature côtière discrète et farouche vivant principalement dans les zones rocheuses, les plages et les abords de certains lacs. Lent mais difficile à repérer, il se fond naturellement dans son environnement et préfère fuir plutôt que se défendre.

Son dos est recouvert de cératine, matière souple et résistante recherchée pour fabriquer des équipements de protection accessibles et durables.`},
{section:'Créatures',title:'Scalvignus',text:`Créature forestière discrète et paisible, reconnaissable à sa silhouette de cerf recouverte d’écailles et à ses larges bois ramifiés. Il évite naturellement les humains et ne se défend qu’en cas de menace.

À la fin de l’hiver, ses bois tombent naturellement et sont parfois récupérés pour leurs propriétés magiques, notamment dans la confection de certains catalyseurs.`},
{section:'Créatures',title:'Échoïde',text:`Créature née d’une ancienne structure runique ayant conservé une part du savoir, des souvenirs et de la personnalité de son créateur. Généralement lié à son lieu d’origine, il peut continuer à protéger, enseigner ou accomplir la fonction pour laquelle la structure avait été conçue.

Avec le temps et la dégradation des runes, sa mémoire peut se fragmenter et le rendre confus, obsessionnel ou dangereux. Certains finissent même par croire qu’ils sont réellement le runomancien dont ils portent l’empreinte. Il demeure une créature dangereuse et imprévisible.`},
{section:'Créatures',title:'Ornicabal',text:`Créature semi-aquatique vivant principalement dans les forêts riveraines. Sociable, joueuse et capable d’être apprivoisée, elle peut devenir brusquement agressive lorsqu’elle défend son territoire ou sa nourriture.

Sa peau couverte de fines écailles hydrophobes la protège de l’humidité et lui permet d’évoluer entre terre et eau. Les écailles perdues naturellement pendant sa croissance servent à fabriquer des équipements imperméables et à certains usages liés à la magie de l’eau.`},
{section:'Société',title:'AMRU',subtitle:'Autorités Magiques du Royaume-Uni',text:`L’AMRU constitue l’autorité centrale chargée de l’administration de la société magique du Royaume-Uni. Elle veille à l’application des lois, à la sécurité de la population, au fonctionnement des institutions et à la régulation des pratiques magiques, créatures, artefacts et activités susceptibles d’affecter l’équilibre du monde magique.

Son autorité s’étend aux individus, organisations et communautés relevant de sa juridiction. Elderwood occupe une place particulière dans cet équilibre : principale institution de formation magique du pays, l’école entretient depuis des siècles des relations étroites avec les autorités britanniques. Malgré son autonomie, elle demeure un interlocuteur essentiel de l’AMRU pour former les nouvelles générations et répondre aux enjeux majeurs de la société magique.`},
{section:'Familles',title:'Caerwyn',subtitle:'Aerwyn · Le serment',text:'Présents aux côtés d’Aerwyn dès la fondation de l’école, les Caerwyn ont fait de la protection d’Elderwood un devoir transmis de génération en génération. Leur nom est associé à l’honneur, au respect du code et à la parole donnée. Ils sont représentés par Seraphine Caerwyn, capitaine de Razeball des Aerwyn.'},
{section:'Familles',title:'Hearthbane',subtitle:'Brumval · Le foyer',text:'Liés à Brumval depuis les premières années d’Elderwood, les Hearthbane sont à l’origine du premier feu de la Grande Salle et de la célèbre Flamme Ouverte. La famille incarne la loyauté, l’unité et la protection de la communauté. Elle est représentée par Petra Hearthbane, élève de quatrième année.'},
{section:'Familles',title:'Valemont',subtitle:'Falcon · Le savoir',text:'Gardiens historiques des archives d’Elderwood, les Valemont ont sauvé les savoirs de l’école durant la Crise des Archives du XIVe siècle. Leur influence s’étend aujourd’hui à l’enseignement, à l’administration et au monde du Razeball. Ils sont représentés par Ebenezer Valemont, héritier d’une lignée aussi brillante qu’exigeante.'},
{section:'Familles',title:'Dravenholt',subtitle:'Venatrix · L’influence',text:'Ancienne famille proche de Venatrix, les Dravenholt évoluent depuis des siècles au cœur des cercles politiques, académiques et mondains du monde magique. Leur pouvoir repose sur la maîtrise des apparences, des réseaux et des décisions prises dans l’ombre. Ils sont représentés par Isolde Dravenholt, élève de cinquième année.'},
{section:'Familles',title:'Belladorn',subtitle:'Alchimie, expérimentation et indépendance',text:'Famille d’alchimistes aussi brillante qu’imprévisible, les Belladorn ont bâti leur réputation sur l’expérimentation, l’herboristerie et le refus des limites imposées par les institutions. Depuis leur domaine dissimulé, la Chaudronnerie, ils poursuivent des recherches parfois dangereuses où la découverte passe souvent avant la prudence.'},
{section:'Familles',title:'Ravenscroft',subtitle:'Runomancie, précision et préparation',text:'Ancienne lignée britannique spécialisée dans la Runomancie, les Ravenscroft sont réputés pour leur maîtrise des structures runiques complexes et leur méthode particulièrement rigoureuse. Leur philosophie tient en une idée : comprendre avant d’intervenir, préparer avant d’agir. Experts des partitions instables et des dangers liés aux runes, ils privilégient toujours la précision à la précipitation.'},
{section:'Familles',title:'Glenhart',subtitle:'Créatures, exploration et connaissance du terrain',text:'Grande famille spécialisée dans l’étude des créatures magiques, les Glenhart ont bâti leur savoir au contact direct du terrain. Deux traditions coexistent dans la lignée : les Compagnons, qui privilégient le soin, la confiance et l’observation rapprochée, et les Arpenteurs, qui parcourent les territoires les plus sauvages afin d’étudier les créatures dans leur milieu naturel.'},
{section:'Personnalités',title:'Arthurius Glenwood',subtitle:'Directeur d’Elderwood',text:'Grand sorcier et protecteur d’Elderwood depuis de nombreuses années, Arthurius Glenwood a consacré une grande partie de sa vie à l’école et à sa sécurité. Son expérience, son calme et son autorité lui ont permis de traverser plusieurs périodes difficiles à la tête de l’établissement. Pour beaucoup, il incarne aujourd’hui la stabilité d’Elderwood.'},
{section:'Personnalités',title:'Edith Grimshaw',subtitle:'Ancienne médicomage d’Elderwood',text:'Lorsque plusieurs élèves furent touchés par une maladie inconnue qui affaiblissait progressivement leur Résonance, Edith Grimshaw tenta une méthode particulièrement risquée : relier temporairement leur magie à la sienne pour absorber une partie de leur fatigue et de leur douleur. Les élèves survécurent, mais Edith ne retrouva jamais entièrement l’usage de sa propre magie. L’infirmerie d’Elderwood porte aujourd’hui son nom.'},
{section:'Personnalités',title:'Alistair Valemont',subtitle:'Haut placé de l’AMRU',text:'Patriarche de la famille Valemont, Alistair est également l’une des figures influentes de l’AMRU. Il défend depuis longtemps une application stricte du Secret magique et considère sa préservation comme l’une des principales responsabilités des institutions sorcières. Son nom est ainsi régulièrement associé aux décisions les plus conservatrices de l’autorité magique britannique.'},
{section:'Personnalités',title:'Cadoc Caerwyn',subtitle:'Celui qui tint la ligne',text:'En 1958, Cadoc Caerwyn et trois autres Aerwyn furent envoyés dans la baie de Lituya après l’apparition de Résonances anormales. Lorsque le réveil d’un Léviathan provoqua un cataclysme, l’ordre d’évacuation fut donné, mais les quatre sorciers refusèrent d’abandonner la communauté présente sur place. Ils maintinrent une barrière de protection pendant trois jours et trois nuits. Cadoc y perdit un bras, mais ne céda rien de ce qu’il estimait juste.'},
{section:'Personnalités',title:'Bénédicte Hearthbane',subtitle:'Le Grand Incendie de Londres',text:'Lors du Grand Incendie de Londres de 1666, Bénédicte Hearthbane participa avec plusieurs Brumval au détournement d’un ancien réseau runique sous la ville afin d’évacuer les familles résonantes prises au piège sans révéler leur existence aux Sans-Flux. Ce dispositif inspira plus tard la création du Tunnel du Faux Pas.'},
{section:'Personnalités',title:'Edgar Ravenscroft',subtitle:'Fondateur de la méthode Ravenscroft',text:'Au XVe siècle, Edgar Ravenscroft fut appelé dans un refuge dont l’accumulation de protections runiques avait engendré un immense Échoïde. Plutôt que de tenter de détruire brutalement la structure, il étudia chacune de ses connexions et les neutralisa progressivement, section après section. Cette intervention devint la base de la Méthode Ravenscroft, encore utilisée pour étudier les systèmes runiques instables.'},
{section:'Personnalités',title:'Rowena Glenhart',subtitle:'L’expédition de Shedwood',text:'En 1890, Rowena Glenhart mena une expédition de quarante jours dans la forêt de Shedwood afin d’étudier la faune magique. Le groupe revint avec l’une des documentations les plus importantes jamais réalisées sur les créatures de la région, mais deux membres disparurent sans laisser de corps ni de matériel. Rowena ne révéla jamais publiquement ce qui s’était produit durant les derniers jours du voyage.'},
{section:'Razeball',title:'Le Raze',text:`Le Razeball, originellement appelé « Razorball » et souvent surnommé « le Raze », est l’un des sports les plus populaires du monde magique. Pratiqué à près d’une centaine de mètres de hauteur, il oppose deux équipes lancées à grande vitesse autour d’une sphère métallique qu’elles doivent envoyer dans le Cœur adverse.

Longtemps joué avec des balais brutaux et sans règles communes, le Razeball moderne naquit véritablement à Elderwood en 1863, lorsque Corvinus Valemont en rédigea le premier règlement et mit au point un dispositif stabilisant les Cœurs utilisés pendant les rencontres. Le sport se diffusa rapidement dans tout le Royaume-Uni et donna naissance, en 1896, à la première Coupe du Monde.

Une équipe aligne six joueurs : un Gardien et cinq joueurs de champ. Les Finishers concluent les actions et tirent à longue distance ; les Playmakers organisent le jeu et créent les ouvertures ; les Enforcers imposent leur présence physique ; les Lights Out se spécialisent dans l’interception et la destruction du jeu adverse. Le Gardien constitue la dernière ligne de défense devant le Cœur.

Le Razeball est aujourd’hui pratiqué à tous les niveaux du monde magique. Des championnats professionnels existent à travers le monde et les meilleures sélections nationales se retrouvent tous les quatre ans. À Elderwood, les quatre maisons s’affrontent toute l’année jusqu’à la grande finale organisée à la fin de l’année scolaire.`}
];
